-- Sprint 1: seed the 14 baseline exercises from workout-app/project/volt-data.js
-- so the library works offline before ExerciseDB is wired up.

insert into public.exercises (id, name, muscle, body_part, equipment, met_value, secondary_muscles, instructions, is_custom) values
('bench',    'Barbell Bench Press',    'Chest',      'Upper body', 'Barbell',    6.0, array['Front Delts','Triceps'],            array['Set shoulder blades back and down on the bench.','Lower the bar to mid-chest with elbows ~45°.','Press up and slightly back toward the rack.'], false),
('incline',  'Incline Dumbbell Press', 'Chest',      'Upper body', 'Dumbbell',   6.0, array['Front Delts','Triceps'],            array['Set the bench to 30–45°.','Lower dumbbells to the outside of your chest.','Press up without letting the weights drift forward.'], false),
('ohp',      'Overhead Press',         'Shoulders',  'Upper body', 'Barbell',    6.0, array['Triceps','Core'],                   array['Brace your glutes and core before the press.','Press the bar in a straight line, moving your head back.','Lock out with biceps by your ears.'], false),
('lateral',  'Lateral Raise',          'Shoulders',  'Upper body', 'Dumbbell',   4.5, array['Traps'],                            array['Lead with your elbows, slight bend in the arm.','Raise to shoulder height, no higher.','Lower slowly — no swinging.'], false),
('pushdown', 'Triceps Rope Pushdown',  'Triceps',    'Upper body', 'Cable',      4.5, array['Forearms'],                         array['Pin elbows to your sides.','Split the rope at the bottom of each rep.','Control the return to stretch.'], false),
('squat',    'Barbell Back Squat',     'Quads',      'Lower body', 'Barbell',    6.5, array['Glutes','Hamstrings','Core'],       array['Bar over mid-foot, big breath, brace.','Sit down between your hips, knees out.','Drive the floor away to stand.'], false),
('rdl',      'Romanian Deadlift',      'Hamstrings', 'Lower body', 'Barbell',    6.5, array['Glutes','Lower Back'],              array['Push hips back with soft knees.','Keep the bar dragging along your thighs.','Stop at hamstring stretch, then stand tall.'], false),
('legpress', 'Leg Press',              'Quads',      'Lower body', 'Machine',    5.5, array['Glutes','Hamstrings'],              array['Feet shoulder-width on the platform.','Lower until thighs near your chest.','Press without locking knees hard.'], false),
('pullup',   'Pull-Up',                'Back',       'Upper body', 'Bodyweight', 8.0, array['Biceps','Forearms'],                array['Start from a dead hang, shoulders engaged.','Pull your chest toward the bar.','Lower with control to full extension.'], false),
('row',      'Barbell Row',            'Back',       'Upper body', 'Barbell',    6.5, array['Biceps','Rear Delts'],              array['Hinge to ~45°, flat back.','Pull the bar to your lower ribs.','Pause, then lower under control.'], false),
('cablerow', 'Seated Cable Row',       'Back',       'Upper body', 'Cable',      5.0, array['Biceps','Rear Delts'],              array['Sit tall, chest up.','Drive elbows back, squeeze shoulder blades.','Let the weight stretch you forward slowly.'], false),
('curl',     'Dumbbell Biceps Curl',   'Biceps',     'Upper body', 'Dumbbell',   4.0, array['Forearms'],                         array['Elbows pinned at your sides.','Curl without swinging your torso.','Lower slowly for full range.'], false),
('lunge',    'Walking Lunge',          'Glutes',     'Lower body', 'Dumbbell',   6.0, array['Quads','Hamstrings'],               array['Long step, torso upright.','Back knee kisses the floor.','Push through the front heel to step through.'], false),
('plank',    'Plank',                  'Core',       'Core',       'Bodyweight', 3.5, array['Shoulders','Glutes'],               array['Elbows under shoulders.','Squeeze glutes, tuck ribs.','Breathe — don’t hold your breath.'], false);
